### ISSUE TITLE
TS-to-YAML environment migration script produces non-functional YAML  

### ISSUE THREAD

**Issue by ybnd** [DSpace/dspace-angular#1525]
**Describe the bug**
The `env:yaml` script nests all TS config under `environment:`, causing it to be ignored when building

**To Reproduce**
1. Add a legacy environment file, e.g. `src/environments/environment.dev.ts`
    ```typescript
    export const environment = {
      rest: {
        ssl: false,
        host: 'localhost',
        port: 8080,
        nameSpace: '/dspace-local',
      },
    };
    ```
2. `yarn env:yaml src/environments/environment.dev.ts config/config.dev.yml` generates the following YAML
      ```yaml
      environment:
        rest:
          ssl: false
          host: localhost
          port: 8080
          nameSpace: /dspace-local
      ```
      **which won't override the default parameters correctly.**
3. Run `yarn start:dev` without any overriding environment variables
    * The generated `src/assets/config.json` will just be `DefaultAppConfig`
    * ...with our migrated config as an extra `environment` object that's never used

**Expected behavior**
* The `env:yaml` script should not nest everything under `environment:`

**Related work**
#1437
