### ISSUE TITLE
Running application with defining configuration ui.nameSpace doesn't work

### ISSUE THREAD

**Issue by atarix83** [DSpace/dspace-angular#1829]
**Describe the bug**
With the main branch running application with defining configuration ui.nameSpace doesn't work properly, while is working properly in the 7.3 release. The problem is the dspace-theme.css is not loaded and the result is the following 
![Schermata da 2022-09-16 10-41-39](https://user-images.githubusercontent.com/2486489/190601151-edb2e8d0-6a82-4cd4-95af-7be948c363c6.png)

**To Reproduce**
1. in the config.dev.yml configure a different namespace for the ui, e.g:
``` 
ui:
  ssl: false
  host: localhost
  port: 4000
  nameSpace: /ui
  rateLimiter:
    windowMs: 60000
    max: 500
```
2. run application with yarn start:dev

**Expected behavior**
The page should be loaded properly when a different namespace than `/` is used

**Related work**
this was alredy fixed in the 7.3 release by this PR https://github.com/DSpace/dspace-angular/pull/1642
