### ISSUE TITLE
Customizability of theme colours

### ISSUE THREAD

**Issue by davide-negretti** [DSpace/dspace-angular#1914]
Bootstrap uses a semantic colour scheme, that associates each colour to a meaning (primary and secondary colour, warning, info...).

The current colour scheme has a few issues that limit its customisability.

First of all, the primary colour of bootstrap is blue, while the primary colour of DSpace is dark grey. This colour has been changed by redefining the `$blue` SASS variable to grey, but a better approach would be to redefine the `$primary` variable instead.

Another problem is that the badges in the MyDSpace use `badge-MEANING` classes to change the badge colour, and this prevents from changing the semantic colour scheme without changing the badge colours.

![image](https://user-images.githubusercontent.com/87638927/196727571-61fc5209-a60a-4cae-91e9-231f6e79ff02.png)

In this case I would create new classes, e.g. `badge-validation` to replace `badge-warning`, thus decoupling the colour from the semantic meaning.

**Comment by davide-negretti** [comment]
@tdonohue I would like to handle this issue, with an estimated effort of 2-4 hours.

**Comment by tdonohue** [comment]
@davide-negretti : This seems reasonable, provided they are minor changes simply to align better with Bootstrap.  That said, these changes would need to be clearly documented, so that people upgrading to the next release of DSpace are not surprised when their theme doesn't work properly (because old styles were renamed).

**Comment by davide-negretti** [comment]
@tdonohue I opened a PR for this task: #1923 

As a further step, I suggest another change. The current situation is:
```scss
$red: // customised theme colour

$theme-colors: (
  // ...
  danger: $red,
  // ...
)

--bs-red: #{$red};

--bs-danger: #{$danger};
```

I suggest this change:
```scss
$red: // original Bootstrap colour                    // RESTORED
$ds-red: // customised theme colour                   // NEW

$theme-colors: (
  // ...
  danger: $ds-red,                                    // BASED ON A NEW VARIABLE
  // ...
)

--bs-red: #{$red};                                    // UNCHANGED
--ds-red: #{$ds-red};                                 // NEW

--bs-danger: #{$danger}; // customised theme colour   // UNCHANGED
```
This change would not affect the semantic colours (e.g. danger), but would allow to use the "normal" colours (e.g. red). At the moment the `--bs-colour` variables are used in very few places so it should be easy to replace them with the new `--ds-colour` variables and I am not expecting conflicts in other forks and customisations of DSpace.
