### ISSUE TITLE
When Extending Theme It gets duplicated multiple times

### ISSUE THREAD

**Issue by misilot** [DSpace/dspace-angular#2346]
**Describe the bug**
When extending the theme to overwrite it duplicates all the elements multiple times. This is with DSpace 7.6. 

So what I did was copy the dspace theme, made it called "theme1" and made my normal changes there. I then created theme2 and want to apply it to specific collections to add additional metadata fields to some of the views. 

It looks like it's rendering the original version, and the extended theme? See the photo below

![image](https://github.com/DSpace/dspace-angular/assets/1446856/1daed516-d3e2-45c3-aa99-3840da918952)

**To Reproduce**
1. Create custom theme by copying the dspace theme (theme1)
2. Enable your new theme1
3. Create a new theme (theme2) that you want to change only `src/themes/theme2/app/item-page/simple/item-types/untyped-item/untyped-item.component.html` in
4. Enable themes in config.yml
```yml
themes:
  - name: theme2
    extends: theme1
    uuid: '6d684812-6d29-4564-8b51-f5670957936b'

  # default theme, based on DSpace
  - name: theme1
```

**Expected behavior**
I would it to only change the elements defined in
