### ISSUE TITLE
Bug: theme matching by handle doesn't work, but uuid does

### ISSUE THREAD

**Issue by misilot** [DSpace/dspace-angular#2348]
**Describe the bug**
Matching on a collection handle does not appear to work for a collection, but using a UUID does work (except for the duplicated elements #2346)

**To Reproduce**

```yml
themes:
  - name: etdr
    extends: krex
    handle: '2097/4'
    # uuid: '6d684812-6d29-4564-8b51-f5670957936b'

  # default theme, based on DSpace
  - name: krex
```

This works though
```yml
themes:
  - name: etdr
    extends: krex
    uuid: '6d684812-6d29-4564-8b51-f5670957936b'

  # default theme, based on DSpace
  - name: krex
```

**Expected behavior**
Theming should be applied to the collection items when using the handle, or the uuid.

**Related work**

**Comment by alexandrevryghem** [comment]
I tried the same with this config, and it worked (I also had to uncomment the `CustomEagerThemeModule` in `src/themes/eager-themes.module.ts`):
```yml
themes:
  - name: custom
    extends: dspace
    handle: '123456789/2'
  - name: dspace
```

Could you maybe go over [these steps](https://wiki.lyrasis.org/display/DSDOC7x/User+Interface+Customization#UserInterfaceCustomization-CreatingaCustomTheme) and check that your theme is correctly set up

**Comment by misilot** [comment]
@alexandrevryghem I believe it's setup correctly? The copy of `dspace` to `krex` seems to work (https://github.com/kstatelibrariesit/dspace-angular/tree/etdr-theme/src/themes/krex) but not the subtheme [etdr](https://github.com/kstatelibrariesit/dspace-angular/tree/etdr-theme/src/themes/etdr) 

I made the repo public incase it would be easier to see where I might have messed up

**Comment by alexandrevryghem** [comment]
@misilot sorry for the late response I was on vacation. Can you try rebasing/merging your branch with the branch from the linked PR and check that both issues are now resolved?

**Comment by misilot** [comment]
@alexandrevryghem I was trying to apply this to the 7.6 branch I have, but it doesn't apply cleanly.

```
git am --show-current-patch=diff
---
 src/app/shared/theme-support/themed.component.ts | 6 +++---
 1 file changed, 3 insertions(+), 3 deletions(-)

diff --git a/src/app/shared/theme-support/themed.component.ts b/src/app/shared/theme-support/themed.component.ts
index 2ff0713f460..920fbba6e56 100644
--- a/src/app/shared/theme-support/themed.component.ts
+++ b/src/app/shared/theme-support/themed.component.ts
@@ -1,10 +1,10 @@
 import {
+  AfterViewInit,
   Component,
   ViewChild,
   ViewContainerRef,
   ComponentRef,
   SimpleChanges,
-  OnInit,
   OnDestroy,
   ComponentFactoryResolver,
   ChangeDetectorRef,
@@ -21,7 +21,7 @@ import { GenericConstructor } from '../../core/shared/generic-constructor';
   styleUrls: ['./themed.component.scss'],
   templateUrl: './themed.component.html',
 })
-export abstract class ThemedComponent<T> implements OnInit, OnDestroy, OnChanges {
+export abstract class ThemedComponent<T> implements AfterViewInit, OnDestroy, OnChanges {
   @ViewChild('vcr', { read: ViewContainerRef }) vcr: ViewContainerRef;
   protected compRef: ComponentRef<T>;

@@ -49,7 +49,7 @@ export abstract class ThemedComponent<T> implements OnInit, OnDestroy, OnChanges
     }
   }

-  ngOnInit(): void {
+  ngAfterViewInit(): void {
     this.destroyComponentInstance();
     this.themeSub = this.themeService.getThemeName$().subscribe(() => {
       this.renderComponentInstance();
```

is what `git am` isn't happy about

**Comment by alexandrevryghem** [comment]
I just tried merging in `themed-component-fixes-main` into `etdr-theme` and it succeeded without any merge conflicts
```bash
 git merge themed-component-fixes-main                                                                                                                                                                  
 Merge made by the 'ort' strategy.
 src/app/shared/theme-support/themed.component.ts | 10 ++++------
 1 file changed, 4 insertions(+), 6 deletions(-)
```

**Comment by misilot** [comment]
Thanks @alexandrevryghem so 

```yml
  - name: etdr
    extends: krex
    uuid: '6d684812-6d29-4564-8b51-f5670957936b'
```
appears to work, but not 

```yml
  - name: etdr
    extends: krex
    handle: '2097/4'
```

However, the duplicating theme element issue did go away!

**Comment by alexandrevryghem** [comment]
I couldn't reproduce at first because I tested it with the classic themed components until I realised you were talking about the `@listableObjectComponent` like `UntypedComponent`, they use a different mechanism to detect the theme. Normal themed components (the ones without decorators) can still be themed by handle. I will try to make PR for this bug as well.

**Comment by alexandrevryghem** [comment]
@misilot I couldn't reproduce this error. I tried with both dynamically created components like `UntypedComponent` and standard themable components like `HeaderNavbarWrapperComponent`, and I still wasn't able to reproduced this error I also tried running it in both prod and dev mode without any luck. Can you provide more info about how you noticed that it didn't work like for which component doesn't it work on your branch and what change would you expect where.

**Comment by misilot** [comment]
@alexandrevryghem 

So I'm trying to add these additional metadata specific components to specific communities (the etdr theme)
https://github.com/kstatelibrariesit/dspace-angular/blob/etdr-theme/src/themes/etdr/app/item-page/simple/item-types/untyped-item/untyped-item.component.html#L65-L75

If I use in my config.yml file
```yaml
themes:
  # Specific Item
  # - name: etdr
  #   extends: krex
  #   handle: '2097/43295'

  - name: etdr
    extends: krex
    handle: '2097/4'

  # default theme, based on DSpace
  - name: krex
    headTags:
      # Insert <link rel="icon" href="assets/krex/images/favicons/favicon.ico" sizes="any"/> into the <head> of the page.
      - tagName: link
        attributes:
          rel: icon
          href: assets/krex/images/favicons/favicon.ico
          sizes: any
```

I get the following results (not working)

![image](https://github.com/DSpace/dspace-angular/assets/1446856/4069a5b4-e44b-492b-ac1e-62218ac52964)


However if I use

```yml
themes:
  - name: etdr
    extends: krex
    uuid: '6d684812-6d29-4564-8b51-f5670957936b'

  # default theme, based on DSpace
  - name: krex
    headTags:
      # Insert <link rel="icon" href="assets/krex/images/favicons/favicon.ico" sizes="any"/> into the <head> of the page.
      - tagName: link
        attributes:
          rel: icon
          href: assets/krex/images/favicons/favicon.ico
          sizes: any
```

It does work as expected, except for the duplicative collections (I don't think I did this)

![image](https://github.com/DSpace/dspace-angular/assets/1446856/86a5abed-c7b0-4be0-bc83-fe24470dcee1)
