### ISSUE TITLE
HEAD requests via the HANDLE urls return a HTTP code status of 200 instead of 301 (redirect)

### ISSUE THREAD

**Issue by amgciadev** [DSpace/dspace-angular#4042]
## Describe the bug
We are seeing differences between DSpace 7.x and DSpace 8.x in returned http code statuses for handle URLs when doing HEAD requests as opposed to GET requests. The following curl examples show that DSpace 7.x returns as expected a 301 whereas DSpace 8.1 return a 200 code instead.

**DSpace 7.6.2:** curl -L -I https://diamond-oa.lib.cam.ac.uk/handle/1812/183 
**DSpace 8.1:** curl -L -I https://diamond-f-dev.lib.cam.ac.uk/handle/1812/183

This affects retrieving metadata via signposting links when using the HEAD command (as recommended) as the status code returned is 200 and redirects are not followed to retrieve the link headers.

This affects the PCI Endorsement Notify workflow (see PR #3735 )

Something must have changed between versions.

## To Reproduce
1. See curl commands above to test across DSpace versions

## Expected behavior
The return response should be 301 for HEAD requests of handle based URLs.

## Related work
Link to any related tickets or PRs here.

**Comment by atarix83** [comment]
@tdonohue  we can't take a look at this

**Comment by AndreaBarbasso** [comment]
@tdonohue, I added a comment that is relevant to this issue on this related PR: https://github.com/DSpace/dspace-angular/pull/4227.

**Comment by tdonohue** [comment]
I've tested today and verified that **this bug ticket is fixed by #4227**.  This Handle redirect issue is essentially the same sort of issue as #4132

**Comment by tdonohue** [comment]
Fixed by #4227.  

**If anyone is encountering this error locally, you have two possible fixes/workarounds:**

1. You can enable SSR (server side rendering) on all paths by using this configuration in your `config.prod.yml` (on frontend)
    ```
    ssr:
      paths: [ '/' ]
    ```
2. Or, alternatively, you can merge in the changes of #4227 (or upgrade to 7.6.4, 8.2 or 9.0 once they are released).  This PR removes the `paths` configuration in favor of an `excludePathPatterns` configuration which only *excludes* specific paths from SSR like this:
    ```
    ssr:
      excludePathPatterns:
        - pattern: "^/communities/[a-f0-9-]{36}/browse(/.*)?$",
          flag: "i"
        - pattern: "^/collections/[a-f0-9-]{36}/browse(/.*)?$"
          flag: "i"
        - pattern: "^/browse/"
        - pattern: "^/search$"
        - pattern: "^/community-list$"
        - pattern: "^/admin/"
        - pattern: "^/processes/?"
        - pattern: "^/notifications/"
        - pattern: "^/statistics/?"
        - pattern: "^/access-control/"
        - pattern: "^/health$"
    ```
